### ISSUE TITLE
Error creating tables in new version of Tables.py

### ISSUE THREAD

**Issue by zanton123** [gdiminin/HaSAPPy#4]
The program terminates with the type error below (the HaSAPPy command script used for running the analysis is attached: [myProj.txt](https://github.com/gdiminin/HaSAPPy/files/791664/myProj.txt))

```
Generation of Tables
	Started: 17-02-21 23:07:19
1) Insertions

	Columns:
	Control_II_ctrl1 | Control_II_ctrl2 | Control_II_ctrl3 | Control_II_ctrl4 | Control_II_ctrl5 | Control_II_ctrl6 | Control_II_ctrl7 | Selected_II_sel1 | Selected_II_sel2 | Selected_II_sel3 | Selected_II_sel4 | Selected_II_sel5 | Selected_II_sel6 | Selected_II_sel7 | Control_II_mean | Selected_II_mean | Selected_II_fold
Traceback (most recent call last):
  File "HaSAPPY_start.py", line 48, in <module>
    Tables.main(analysis)
  File "/media/HDD/HaSAPPy/program/Tables.py", line 175, in main
    tables.append(create_table(Info,GroupAnalysis,summary,keys,filters,table))
  File "/media/HDD/HaSAPPy/program/Tables.py", line 129, in create_table
    string = '\n\tFilters:%s\n\t' % (' | ').join(filters)
TypeError: sequence item 0: expected string, dict found
```

**Comment by gdiminin** [comment]
The problem was fixed. Thanks for the suggestion
