### ISSUE TITLE
Issue with generating an excel table

### ISSUE THREAD

**Issue by tthye1** [gdiminin/HaSAPPy#7]
When I run the analysis I got the following error when the script tries to generate the excel table.

Kind regards,  Thorsten

Generation of Excel table
	Started: 18-12-18 10:30:27
Traceback (most recent call last):
  File "HaSAPPy/HaSAPPY.py", line 59, in <module>
    Tables.main(analysis)
  File "build/bdist.linux-x86_64/egg/HaSAPPy/Tables.py", line 230, in main
    table.to_excel(writer, sheet_name= table.name,na_rep = 'NaN')
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 1464, in to_excel
    startrow=startrow, startcol=startcol)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/excel.py", line 1512, in write_cells
    wks = self.book.add_worksheet(sheet_name)
  File "build/bdist.linux-x86_64/egg/xlsxwriter/workbook.py", line 174, in add_worksheet
  File "build/bdist.linux-x86_64/egg/xlsxwriter/workbook.py", line 695, in _add_sheet
  File "build/bdist.linux-x86_64/egg/xlsxwriter/workbook.py", line 745, in _check_sheetname
xlsxwriter.exceptions.InvalidWorksheetName: Excel worksheet name '(all,II,raw),(Unsel,II,sum),(Sel,II,sum),(all,KI,fold)' must be <= 31 chars.

**Comment by gdiminin** [comment]
Thanks for letting me know of this problem
Issue is fixed in the last update.
Best regards,
Giulio
